name: tests-tickets
on:
  pull_request:
    paths:
      - 'tickets/**'
jobs:
  bulid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
