name: tests-payments
on:
  pull_request:
    paths:
      - 'payments/**'
jobs:
  bulid:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
